import Head from "next/head";
import Navbar from "../components/Navbar";

import "@/styles/globals.css";
import "../../styles/custom.css";
import Footer from "../components/Footer";
import { ToastContainer } from "react-toastify";

export default function App({ Component }) {
  return (
    <>
      <Head>
        <title>commodityze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon1.png" type="image/png/svg" />
      </Head>
      <div className="cursor-auto">
        <Navbar />
        <Component />
        <Footer />
        <ToastContainer />

      </div>
    </>
  );
}
